import type { LucideIcon } from 'lucide-react';
import {
  HeartPulse,
  Wallet,
  TrendingUp,
  Flame,
  Sprout,
  BarChart3,
  Dumbbell,
  Shield,
  BookOpen,
  PersonStanding,
  Flower2,
  Droplets,
  Target,
  PenTool,
  Palette,
  Music,
  Moon,
  Apple,
  Paintbrush,
  Pill,
  Dog,
  NotebookPen,
  Coffee,
  Footprints,
  Brain,
  Heart,
  Sunrise,
  Book,
  Guitar,
  CigaretteOff,
  WineOff,
  TvMinimal,
  ClipboardList,
  Leaf,
  UtensilsCrossed,
  CandyOff,
  ChefHat,
  HandHeart,
  TreePine,
  ShowerHead,
  StretchHorizontal,
  Globe,
  ShoppingCart,
  PiggyBank,
  Timer,
  PhoneOff,
  MessageCircleOff,
  Sparkles,
  ListChecks,
  CalendarCheck,
} from 'lucide-react';

/** Lucide kebab-case name → Component mapping */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  'heart-pulse': HeartPulse,
  wallet: Wallet,
  'trending-up': TrendingUp,
  flame: Flame,
  sprout: Sprout,
  'bar-chart-3': BarChart3,
  dumbbell: Dumbbell,
  shield: Shield,
  'book-open': BookOpen,
  'person-standing': PersonStanding,
  'flower-2': Flower2,
  droplets: Droplets,
  target: Target,
  'pen-tool': PenTool,
  palette: Palette,
  music: Music,
  moon: Moon,
  apple: Apple,
  paintbrush: Paintbrush,
  pill: Pill,
  dog: Dog,
  'notebook-pen': NotebookPen,
  coffee: Coffee,
  footprints: Footprints,
  brain: Brain,
  heart: Heart,
  sunrise: Sunrise,
  book: Book,
  guitar: Guitar,
  'cigarette-off': CigaretteOff,
  'wine-off': WineOff,
  'tv-minimal': TvMinimal,
  'clipboard-list': ClipboardList,
  leaf: Leaf,
  'utensils-crossed': UtensilsCrossed,
  'candy-off': CandyOff,
  'chef-hat': ChefHat,
  'hand-heart': HandHeart,
  'tree-pine': TreePine,
  'shower-head': ShowerHead,
  'stretch-horizontal': StretchHorizontal,
  globe: Globe,
  'shopping-cart': ShoppingCart,
  'piggy-bank': PiggyBank,
  timer: Timer,
  'phone-off': PhoneOff,
  'message-circle-off': MessageCircleOff,
  sparkles: Sparkles,
  'list-checks': ListChecks,
  'calendar-check': CalendarCheck,
};

/** Icons available in the Habit Icon Picker */
export const ICON_OPTIONS = [
  'dumbbell',
  'book-open',
  'person-standing',
  'flower-2',
  'droplets',
  'target',
  'pen-tool',
  'palette',
  'music',
  'sprout',
  'moon',
  'apple',
  'paintbrush',
  'pill',
  'dog',
  'notebook-pen',
  'coffee',
  'footprints',
  'brain',
  'heart',
  'sunrise',
  'book',
  'guitar',
  'flame',
] as const;
